services:
  backend:
    build: .
    ports:
      - "5050:5062"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - Jwt__SecretKey=${JWT_SECRET}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pawsdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
